# 网站的基本信息
site:
  tab: BitTerminal # 浏览器标签栏上显示的文本
  title: BitTerminal # 网站的标题
  description: BitTerminal —— A coder's personal recorder. # 网站的描述，用于SEO等
  language: zh # 网站的语言，例如 "en" 是英文
  favicon: /favicon.png # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark # 代码块的主题 https://expressive-code.com/guides/themes/
  date_format: ddd MMM DD YYYY # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    - id: home # 菜单项的唯一标识符
      text: 主页 | Home # 菜单项显示的文本
      href: / # 菜单项链接的地址
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: 作者 | Author
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: record
      text: 记录 | Records
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: 全部 - All
          href: /blog
          svg: "material-symbols:news-outline-rounded"
          target: _self
        - id: ai_agent
          text: AI智能体 - AI Agent
          href: /blog/category/AI智能体 - AI Agent # 根据分类链接到不同的页面
          svg: "material-symbols:news-outline-rounded"
          target: _self
        - id: cpp_style
          text: C++风格 - C++ Style
          href: /blog/category/C++风格 - C++ Style # 根据分类链接到不同的页面
          svg: "material-symbols:news-outline-rounded"
          target: _self
        - id: essay
          text: 随笔 - Essay
          href: /blog/category/随笔 - Essay
          svg: "material-symbols:news-outline-rounded"
          target: _self
        # 子菜单项配置
    - id: project
      text: 仓库 | Repos
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: 挚友 | Friends
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    # - id: contact
    #   text: 邮箱 | Email
    #   href: "mailto:althenesc@outlook.com"
    #   target: _blank # 在新标签页打开
    #   svg: "material-symbols:attach-email-outline-rounded"

# 用户的个人信息
user:
  name: Altasc # 用户名
  site: "https://altasc.github.io" # 用户的网站链接
  avatar: /profile.png # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      - href: "https://github.com/Altasc"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://x.com/althenesc"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-x-line"
      - href: "https://space.bilibili.com/456134934"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "mailto:althenesc@outlook.com" # 链接
        ariaLabel: Email # 图标的可访问性标签
        title: Email # 图标的悬浮标题
        svg: "lucide:mail"

  footer:
    social:
      - href: "https://github.com/Altasc"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://x.com/althenesc"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-x-line"
      - href: "https://space.bilibili.com/456134934"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "mailto:althenesc@outlook.com" # 链接
        ariaLabel: Email # 图标的可访问性标签
        title: Email # 图标的悬浮标题
        svg: "lucide:mail"
